language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t bernardo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bernardo/docker-react npm run test